const PROJECTS = [
  {
    id: "01",
    topic: "ModLifes",
    description:
      "CS22 Integrated project I. A social media for KMUTT's student.",
    year: "2023",
    stack: [
      "React",
      "TypeScript",
      "Node.js",
      "ChakraUI",
      "Prisma",
      "Axios",
      "PostgreSQL",
      "Figma",
    ],
    src: "https://github.com/CSSIT22/studentlife",
    alt: "modlifes",
    image:"/images/modlifes.png",
  },
  {
    id: "02",
    topic: "Paigun",
    description: "Integrated project II. A ride-sharing application.",
    year: "2023",
    stack: ["Flutter", "Supabase", "Onesignal", "FCM", "Firebase", "Figma"],
    src: "https://github.com/wuhoops/Paigun",
    alt: "paigun",
    image:"/images/paigun.png",
  },
  {
    id: "03",
    topic: "Checkmate",
    description: "To-do list with a mini challenge feature.",
    year: "2023",
    stack: ["Flutter", "Firebase", "Figma"],
    src: "https://github.com/wuhoops/Checkmate",
    alt: "checkmate",
    image:"/images/checkmate.png",
  },
  // {
  //   id: "04",
  //   topic: "Wuhoops portfolio",
  //   description: "My portfolio website.",
  //   year: "2023",
  //   stack: ["React", "Tailwind", "MUI"],
  //   src: "https://github.com/wuhoops",
  //   alt: "wuhoops-portfoilo",
  //   image:"/images/wuhoops.png",
  // },
  {
    id: "05",
    topic: "929EXAM",
    description: "CSC105 web-app development exam.",
    year: "2022",
    stack: ["React", "JavaScript", "Bootstrap", "ReactStrap"],
    src: "https://github.com/wuhoops/929EXAM",
    alt: "929exam",
    image:"/images/929exam.png",
  },
];

export default PROJECTS;
