const PROJECTS = [
    {
        id: "01",
        topic: "ModLifes",
        description:
            "CS22 Integrated project I. A social media for KMUTT's student.",
        year: "2023",
        stack: [
            "React",
            "TypeScript",
            "Node.js",
            "ChakraUI",
            "Prisma",
            "Axios",
            "PostgreSQL",
            "Figma",
        ],
        res: ["Team leader of shortnote module.", "Design UX/UI wireframe.", "Design ER diagram.", "Developed on both frontend and backend of the Shortnote module."],
        src: "https://github.com/CSSIT22/studentlife",
        alt: "modlifes",
        image: "/images/modlifes.png",
        design: "https://www.figma.com/file/GwCKbsdQ7s5niNkTe8M1ZP/Shortnote_wireframe?type=design&mode=design&t=kJIaoc0LevSb7uWb-1"
    },
    {
        id: "02",
        topic: "Paigun",
        description: "Integrated project II. A ride-sharing application.",
        year: "2023",
        stack: ["Flutter", "Supabase", "Onesignal", "FCM", "Firebase", "Figma"],
        res: ["Developed on both frontend and backend.", "Design UX/UI.", "Implement push notification system using Firebase cloud masseging integrated with Onesignal."],
        src: "https://github.com/oupsn/Paigun",
        alt: "paigun",
        image: "/images/paigun.png",
        design:
            "https://www.figma.com/file/qAisD2zLDVqHujvx5vSnTT/Pai-Gun?type=design&node-id=0%3A1&mode=design&t=kJIaoc0LevSb7uWb-1",
    },
    {
        id: "03",
        topic: "Checkmate",
        description: "CSC234 User-Centered Mobile App. Dev. & CSC231 Agile Software Engineering, A to-do list applicaiton with a mini challenge feature.",
        year: "2023",
        stack: ["Flutter", "Firebase", "Figma"],
        src: "https://github.com/oupsn/Checkmate",
        res: ["Design UX/UI.", "Developed on frontend for setting feature."],
        alt: "checkmate",
        image: "/images/checkmate.png",
        design: "https://www.figma.com/file/sru5MA1RVTfbMzejZSjH8Y/Checkmate?type=design&node-id=0%3A1&mode=design&t=kJIaoc0LevSb7uWb-1"
    },
    {
        id: "07",
        topic: "Interv [in progress]",
        description: "Secret management CLI.",
        year: "2023",
        stack: ["React", "Typescript", "Golang", "Go fiber", "PostgreSQL"],
        src: "",
        alt: "Interv",
        image: "/images/interv.png",
    },
    {
        id: "06",
        topic: "Silenda [in progress]",
        description: "Secret management CLI.",
        year: "2023",
        stack: ["Golang", "Go fiber", "Cobra", "PostgreSQL"],
        src: "https://github.com/oupsn/silenda",
        alt: "Silenda",
        image: "",
    },
    {
        id: "04",
        topic: "Oupsn portfolio",
        description: "My portfolio website.",
        year: "2023",
        stack: ["React", "TypeScript", "Tailwind", "MUI"],
        src: "https://github.com/oupsn/wuhoops_port",
        alt: "oupsn-portfoilo",
        image: "/images/oupsn.png",
    },
    {
        id: "05",
        topic: "Linkmap",
        description: "A links, contacts and social medias sharing web application.",
        year: "2023",
        stack: ["Next.js", "Typescript", "TailwindCSS", "Go", "Go Fiber", "PostgreSQL"],
        res: ["Developed on both frontend and backend.", "Develop backend with Hexagonal architecture.", "Design database on relational database"
        ],
        src: "https://github.com/oupsn/linkmap-backend",
        alt: "linkmap",
        image: "/images/linkmap.png",
    },
    {
        id: "08",
        topic: "Url shortener",
        description: "A url shortener web application.",
        year: "2023",
        stack: ["Next.js", "Typescript", "TailwindCSS", "Go", "Go Fiber", "Supabase"],
        res: ["Developed on both frontend and backend.", "Design database on relational database"],
        src: "https://github.com/oupsn/url-shortener",
        alt: "url-shortener",
        image: "/images/url-shortener.png",
    },
];

export default PROJECTS;
